const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const DEFAULT = 500;
const SUCCESS = 200;
const DUPLICATE_RECORD = 11000;

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  DEFAULT,
  SUCCESS,
  DUPLICATE_RECORD,
};
